workflows:
  android-release:
    name: Android Release (Optimized APK)
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      
      - name: Get Flutter packages
        script: |
          flutter packages pub get

      - name: Build Android Release APK (Split by ABI)
        script: |
          flutter build apk --release --split-per-abi

    artifacts:
      - build/**/outputs/**/*.apk
      - flutter_drive.log
