class LocalizationService {
  static final Map<String, Map<String, String>> _localizedValues = {
    'English': {
      'welcome_back': 'Welcome Back',
      'personal_info': 'PERSONAL INFO.',
      'settings': 'SETTINGS.',
      'edit': 'Edit',
      'save': 'Save',
      'full_name': 'FULL NAME',
      'username': 'USERNAME',
      'age': 'AGE',
      'phone': 'PHONE',
      'gender': 'GENDER',
      'bio': 'BIO',
      'logout': 'Logout',
      'last_seen': 'Last Seen',
      'read_receipts': 'Read Receipts',
      'app_lock': 'App Lock',
      'notifications': 'Notifications',
      'language': 'Language',
      'blocked_users': 'Blocked Users',
      'share_profile': 'Share Profile',
      'select_language': 'SELECT LANGUAGE.',
      'public_visibility': 'Public Visibility',
    },
    'Hindi (हिन्दी)': {
      'welcome_back': 'वापசி पर स्वागत है',
      'personal_info': 'व्यक्तिगत जानकारी',
      'settings': 'सेटिंग्स',
      'edit': 'संपादन करें',
      'save': 'सहेजें',
      'full_name': 'पूरा नाम',
      'username': 'उपयोगकर्ता नाम',
      'age': 'आयु',
      'phone': 'फ़ोन',
      'gender': 'लिंग',
      'bio': 'बायो',
      'logout': 'लॉग आउट',
      'last_seen': 'पिछली बार देखा गया',
      'read_receipts': 'पढ़ी गई रसीदें',
      'app_lock': 'ऐप लॉक',
      'notifications': 'सूचनाएं',
      'language': 'भाषा',
      'blocked_users': 'अवरुद्ध उपयोगकर्ता',
      'share_profile': 'प्रोफ़ाइल साझा करें',
      'select_language': 'भाषा चुनें',
      'public_visibility': 'सार्वजनिक दृश्यता',
    },
    'Tamil (தமிழ்)': {
      'welcome_back': 'நல்வரவு',
      'personal_info': 'தனிப்பட்ட தகவல்',
      'settings': 'அமைப்புகள்',
      'edit': 'திருத்து',
      'save': 'சேமி',
      'full_name': 'முழு பெயர்',
      'username': 'பயனர் பெயர்',
      'age': 'வயது',
      'phone': 'தொலைபேசி',
      'gender': 'பாலினம்',
      'bio': 'சுயவிவரம்',
      'logout': 'வெளியேறு',
      'last_seen': 'கடைசியாக பார்த்தது',
      'read_receipts': 'வாசிப்பு ரசீதுகள்',
      'app_lock': 'ஆப் லாக்',
      'notifications': 'அறிவிப்புகள்',
      'language': 'மொழி',
      'blocked_users': 'தடைசெய்யப்பட்ட பயனர்கள்',
      'share_profile': 'சுயவிவரத்தைப் பகிரவும்',
      'select_language': 'மொழியைத் தேர்ந்தெடுக்கவும்',
      'public_visibility': 'பொதுத் தெரிவுநிலை',
    },
  };

  static String translate(String key, String language) {
    return _localizedValues[language]?[key] ??
        _localizedValues['English']![key]!;
  }
}
